"""
HTML to PPTX Converter

This module provides the reverse direction of the bridge: converting the
HTML slides generated by this library (or any HTML following the same
structure) back into a PowerPoint (.pptx) file.
"""

import os
import re

from .html_parsers import parse_slide_html
from .pptx_generators import build_presentation


def _natural_key(filename):
    """Sort key so slide2 < slide10."""
    return [int(part) if part.isdigit() else part for part in re.split(r'(\d+)', filename)]


class HTMLToPPTXConverter:
    """Main converter class for HTML to PPTX conversion."""

    def convert_file(self, html_dir: str, output_path: str):
        """Convert a directory of slide HTML files into a single PPTX.

        Args:
            html_dir: Directory containing the slides/ subdirectory
                produced by the forward conversion.
            output_path: Path of the .pptx file to write.

        Returns:
            Dict describing the conversion result.
        """
        slides_dir = os.path.join(html_dir, 'slides')
        if not os.path.isdir(slides_dir):
            raise FileNotFoundError(f"Slides directory not found: {slides_dir}")

        slide_files = sorted(
            (f for f in os.listdir(slides_dir) if f.endswith('.html')),
            key=_natural_key,
        )
        if not slide_files:
            raise ValueError(f"No slide HTML files found in {slides_dir}")

        slide_models = []
        for filename in slide_files:
            model = parse_slide_html(os.path.join(slides_dir, filename))
            model['_html_file'] = filename
            slide_models.append(model)

        prs = build_presentation(slide_models, html_dir, output_path)

        return {
            'html_dir': html_dir,
            'output_file': output_path,
            'slides_count': len(slide_models),
            'slide_size_px': (prs.slide_width, prs.slide_height),
        }

    def convert(self, input_path: str, output_path: str = None):
        """Convert an HTML directory (or a single slide HTML file) to PPTX.

        Args:
            input_path: HTML directory containing slides/, or a single
                slide HTML file.
            output_path: Target .pptx path (defaults to '<name>.pptx'
                next to the input).
        """
        if os.path.isfile(input_path) and input_path.endswith('.html'):
            html_dir = os.path.dirname(os.path.dirname(os.path.abspath(input_path)))
        elif os.path.isdir(input_path):
            html_dir = input_path
        else:
            raise FileNotFoundError(f"Input not found or unsupported: {input_path}")

        if not output_path:
            output_path = os.path.join(
                os.path.dirname(os.path.abspath(html_dir)) or '.',
                os.path.basename(os.path.normpath(html_dir)) + '.pptx',
            )
        return self.convert_file(html_dir, output_path)


def convert_html_to_pptx(html_dir: str, output_path: str = None):
    """Convenience function to convert HTML slides back to a PPTX file."""
    return HTMLToPPTXConverter().convert(html_dir, output_path)


def main():
    """Command line interface."""
    import argparse

    parser = argparse.ArgumentParser(description='Convert generated HTML slides back to a PPTX file.')
    parser.add_argument('input', help='HTML directory containing slides/ (or a single slide HTML file)')
    parser.add_argument('--output', '-o', help='Output .pptx path')

    args = parser.parse_args()

    try:
        result = convert_html_to_pptx(args.input, args.output)
    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")
        return 1

    print(f"Converted {result['slides_count']} slides from {result['html_dir']}")
    print(f"Output file: {result['output_file']}")
    return 0


if __name__ == "__main__":
    exit(main())
