[package]
name = "worker-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
tao = "0.16"
wry = "0.24"
tray-icon = "0.2"
tray-menu = "0.1"
image = "0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mixpipe = "0.1.2"
once_cell = "1"
dirs = "5"
base64 = "0.22"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
include_dir = "0.7"
nokhwa = { version = "0.10", features = ["input-native"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

[build-dependencies]
embed-resource = "3.0"
